package com.rnr.deenfocus.tajweed

import java.io.File
import java.util.UUID
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test

/**
 * Phase 3 Android validation pass — pure-Kotlin algorithm parity with the iOS
 * Swift ports (RunnerTests.swift). Covers everything that doesn't require a
 * live ONNX model or a device microphone: mel bucketing, CTC decode/align,
 * tokenizer round-trip, and lexical scoring helpers.
 */
class TajweedAlgorithmTest {

    @Test
    fun ctcDecoderCollapsesRepeatsAndBlanks() {
        val blank = CtcDecoder.BLANK_ID
        val ids = listOf(blank, 5, 5, blank, 6, 6, 6, blank, blank, 7)
        assertEquals(listOf(5, 6, 7), CtcDecoder.collapse(ids))
    }

    @Test
    fun melFrontendProducesExpectedFrameCountAndBucket() {
        val sampleCount = MelFrontend.SAMPLE_RATE // 1 second of audio
        val pcm = FloatArray(sampleCount) { i -> kotlin.math.sin(i * 0.01).toFloat() }
        val result = MelFrontend.logMel(pcm)
        assertEquals(MelFrontend.N_MELS * result.time, result.features.size)
        assertTrue(result.time > 0)

        val bucket = MelFrontend.padToBucket(result.features, result.time)
        assertTrue(bucket.bucketT >= result.time)
        assertEquals(MelFrontend.N_MELS * bucket.bucketT, bucket.padded.size)
        assertTrue(listOf(80, 160, 320, 640, 1280, 2560, 4800).contains(bucket.bucketT))
    }

    /**
     * Golden-vector parity check against tajweed-lab/web/asr/mel.py (the Python reference
     * the ONNX encoder was actually calibrated against — see COREML_CONTRACT.md's "mel
     * parity gate"). Values below were generated by running the reference on the exact
     * same synthetic 440 Hz tone: see the Phase 3 validation notes in
     * memory/features/tajweed/overview.md for the generating command.
     */
    @Test
    fun melFrontendMatchesPythonReferenceOnSyntheticTone() {
        val n = MelFrontend.SAMPLE_RATE
        val pcm = FloatArray(n) { i ->
            val t = i.toDouble() / MelFrontend.SAMPLE_RATE
            (0.3 * kotlin.math.sin(2.0 * Math.PI * 440.0 * t)).toFloat()
        }
        val result = MelFrontend.logMel(pcm)
        assertEquals(101, result.time)

        val expected = mapOf(
            (0 to 0) to 5.030645,
            (0 to 1) to 3.264629,
            (0 to 50) to -0.196291,
            (0 to 99) to 4.572105,
            (10 to 0) to 5.151812,
            (10 to 1) to 3.513548,
            (10 to 50) to -0.196221,
            (10 to 99) to 4.576383,
            (40 to 0) to 7.199261,
            (40 to 1) to 4.668607,
            (40 to 50) to -0.189172,
            (40 to 99) to 2.038765,
            (79 to 0) to 8.097102,
            (79 to 1) to 5.592010,
            (79 to 50) to -0.156101,
            (79 to 99) to 0.117211,
        )
        for ((key, expectedValue) in expected) {
            val (m, t) = key
            val actual = result.features[m * result.time + t]
            assertEquals(
                "mel[$m,$t] should match Python reference",
                expectedValue,
                actual.toDouble(),
                0.01,
            )
        }
    }

    @Test
    fun melFrontendRejectsTooShortAudio() {
        val tooShort = FloatArray(10)
        try {
            MelFrontend.logMel(tooShort)
            fail("Expected TajweedNativeException")
        } catch (e: TajweedNativeException) {
            assertEquals(TajweedErrorCode.AUDIO_TOO_SHORT, e.code)
        }
    }

    @Test
    fun melFrontendRejectsAudioLongerThanBucketLimit() {
        val frames = 4900
        val features = FloatArray(MelFrontend.N_MELS * frames)
        try {
            MelFrontend.padToBucket(features, frames)
            fail("Expected TajweedNativeException")
        } catch (e: TajweedNativeException) {
            assertEquals(TajweedErrorCode.AUDIO_TOO_LONG, e.code)
        }
    }

    @Test
    fun ctcAlignerProducesMonotonicIntervalsForSyntheticLogprobs() {
        // CtcAligner hardcodes blankId = 1024 (same as iOS), so the synthetic vocab
        // must be wider than that even though only 3 ids are actually exercised.
        val blank = CtcAligner.BLANK_ID
        val vocab = blank + 1
        val t = 8
        val logprobs = Array(t) { FloatArray(vocab) { -5f } }
        val favored = mapOf(0 to 0, 1 to 0, 2 to 0, 3 to 1, 4 to 1, 5 to 1, 6 to blank, 7 to blank)
        for (i in 0 until t) {
            logprobs[i][favored.getValue(i)] = 0f
        }
        val intervals = CtcAligner.forcedAlign(logprobs, listOf(0, 1))
        assertEquals(listOf(0, 1), intervals.map { it.tokenId })
        // tokenIndex (position within the input tokenIds list) is what word-grouping keys
        // off — must track tokenId 1:1 here since there are no duplicate ids in this vocab.
        assertEquals(listOf(0, 1), intervals.map { it.tokenIndex })
        assertTrue(intervals[0].endFrame <= intervals[1].startFrame + 1)
        assertTrue(intervals[1].endFrame > intervals[0].startFrame)
    }

    @Test
    fun lexicalTokenReportMatchesAdr006Shape() {
        val expected = listOf("بِسْمِ", "اللَّهِ")
        val hypothesis = listOf("بِسْمِ", "اللَّهِ")
        val tokens = TajweedLexicalScoring.lexicalTokenReport(expected, hypothesis)
        assertEquals(2, tokens.size)
        val allowedKeys = setOf(
            "text", "status", "prob", "startSec", "endSec", "lexical", "pronunciation",
        )
        for (token in tokens) {
            assertTrue(token["text"] is String)
            assertTrue(token["status"] as String == "ok")
            assertEquals("match", token["lexical"])
            assertTrue(
                "Unexpected key in ${token.keys} — no platform-specific fields allowed per ADR-006",
                allowedKeys.containsAll(token.keys),
            )
        }
    }

    @Test
    fun wordAccuracyIsOneForExactMatch() {
        val words = listOf("بِسْمِ", "اللَّهِ", "الرَّحْمَٰنِ")
        assertEquals(1.0, TajweedLexicalScoring.wordAccuracyScore(words, words), 0.0001)
    }

    /**
     * Lexical-first: wordAccuracy counts lexical matches only. Pronunciation severity
     * (minor/major on a matched word) must NOT reduce the percentage.
     */
    @Test
    fun wordAccuracyFromTokensIsLexicalOnlyIgnoringPronunciationSeverity() {
        val tokens = listOf(
            mapOf("text" to "بِسْمِ", "status" to "ok", "lexical" to "match", "pronunciation" to "ok"),
            mapOf("text" to "اللَّهِ", "status" to "minor", "lexical" to "match", "pronunciation" to "minor"),
            mapOf("text" to "الرَّحْمَٰنِ", "status" to "major", "lexical" to "match", "pronunciation" to "major"),
            mapOf("text" to "الرَّحِيمِ", "status" to "miss", "lexical" to "miss", "pronunciation" to null),
        )
        // 3 of 4 expected words were lexically matched (ok/minor/major combined UI status).
        assertEquals(0.75, TajweedLexicalScoring.wordAccuracyFromTokens(tokens, 4), 0.0001)
    }

    @Test
    fun wordAccuracyFromTokensHandlesEmptyExpected() {
        assertEquals(1.0, TajweedLexicalScoring.wordAccuracyFromTokens(emptyList(), 0), 0.0001)
        val extraOnly = listOf(
            mapOf("text" to "زَائِد", "status" to "extra", "lexical" to "extra", "pronunciation" to null),
        )
        assertEquals(0.0, TajweedLexicalScoring.wordAccuracyFromTokens(extraOnly, 0), 0.0001)
    }

    /**
     * Regression: reciting a completely different ayah (zero shared words after
     * normalize) must yield near-zero lexical accuracy — the failure mode that
     * forced-align-first scoring produced 75–100% on.
     */
    @Test
    fun completelyDifferentAyahYieldsZeroLexicalAccuracy() {
        val expected = TajweedLexicalScoring.splitWords("قُلْ هُوَ اللَّهُ أَحَدٌ")
        val hypothesis = TajweedLexicalScoring.splitWords("مَالِكِ يَوْمِ الدِّينِ")
        val ops = TajweedLexicalScoring.alignWords(expected, hypothesis)
        assertEquals(0, ops.count { it.op == TajweedLexicalScoring.LexicalOp.MATCH })
        assertTrue(ops.any { it.op == TajweedLexicalScoring.LexicalOp.SUB || it.op == TajweedLexicalScoring.LexicalOp.MISS })
        val tokens = TajweedLexicalScoring.tokensFromAlignment(ops)
        assertFalse(tokens.any { it["status"] == "ok" || it["status"] == "minor" || it["status"] == "major" })
        assertTrue(tokens.any { it["status"] == "sub" || it["status"] == "miss" })
        assertEquals(0.0, TajweedLexicalScoring.wordAccuracyFromTokens(tokens, expected.size), 0.0001)
        assertEquals(0.0, TajweedLexicalScoring.wordAccuracyScore(expected, hypothesis), 0.0001)
    }

    @Test
    fun substitutionStatusIsDistinctFromMajorPronunciation() {
        val ops = TajweedLexicalScoring.alignWords(
            listOf("قُلْ", "هُوَ"),
            listOf("مَالِكِ", "يَوْمِ"),
        )
        val tokens = TajweedLexicalScoring.tokensFromAlignment(ops)
        assertTrue(tokens.all { it["status"] == "sub" })
        assertTrue(tokens.all { it["lexical"] == "sub" })
        assertTrue(tokens.all { it["pronunciation"] == null })
        // Combined UI "major" means bad pronunciation of a *matched* word — not substitution.
        assertFalse(tokens.any { it["status"] == "major" })
    }

    /**
     * Matched words keep a separate pronunciation field; UI status mirrors it, but
     * lexical accuracy still counts the match even when pronunciation is "major".
     */
    @Test
    fun matchedWordPreservesPronunciationSeparatelyFromLexicalAccuracy() {
        val base = TajweedLexicalScoring.tokenMap(
            text = "قُلْ",
            status = "ok",
            lexical = "match",
            pronunciation = "ok",
            prob = 1.0f,
        ).toMutableMap()
        val badPron = PronunciationHeadModel.statusForProb(0.2f) // "major"
        base["status"] = badPron
        base["pronunciation"] = badPron
        base["prob"] = 0.2f

        assertEquals("match", base["lexical"])
        assertEquals("major", base["pronunciation"])
        assertEquals("major", base["status"])
        assertEquals(1.0, TajweedLexicalScoring.wordAccuracyFromTokens(listOf(base), 1), 0.0001)
    }

    @Test
    fun alignWordsDetectsMissAndExtra() {
        val ops = TajweedLexicalScoring.alignWords(
            listOf("أ", "ب", "ج"),
            listOf("أ", "ج", "د"),
        )
        // A match, B miss or A-B-C vs A-C-D → A match, B miss, C match? 
        // Actually: أ=أ match, ب vs ج = sub, ج vs د = sub — or miss+extra depending on costs.
        // Equal-cost: replace is preferred in our backtrace when cost=1 vs delete+insert=2.
        assertEquals(1, ops.count { it.op == TajweedLexicalScoring.LexicalOp.MATCH })
        assertTrue(
            ops.any { it.op == TajweedLexicalScoring.LexicalOp.SUB } ||
                (ops.any { it.op == TajweedLexicalScoring.LexicalOp.MISS } &&
                    ops.any { it.op == TajweedLexicalScoring.LexicalOp.EXTRA }),
        )
    }

    @Test
    fun pieceWordIndicesGroupsBySentencePieceWordStart() {
        // ids where 1 and 3 start words (▁), 2 continues
        val ids = listOf(1, 2, 3)
        val indices = TajweedLexicalScoring.pieceWordIndices(ids) { id -> id == 1 || id == 3 }
        assertEquals(listOf(0, 0, 1), indices.toList())
    }

    @Test
    fun arabicNormalizationStripsDiacriticsForComparison() {
        val withDiacritics = "بِسْمِ"
        val without = "بسم"
        assertEquals(
            TajweedLexicalScoring.normalizeArabic(withDiacritics),
            TajweedLexicalScoring.normalizeArabic(without),
        )
    }

    /** Uthmani dagger-alif form ↔ Imlaei full-alef form. */
    @Test
    fun normalizeArabicMapsDaggerAlifMalikToImlaei() {
        val uthmani = "مَٰلِكِ" // U+0670 dagger alif
        val imlaei = "مَالِكِ"
        assertEquals("مالك", TajweedLexicalScoring.normalizeArabic(uthmani))
        assertEquals("مالك", TajweedLexicalScoring.normalizeArabic(imlaei))
        assertEquals(
            TajweedLexicalScoring.normalizeArabic(uthmani),
            TajweedLexicalScoring.normalizeArabic(imlaei),
        )
    }

    /** Alef wasla ٱ ↔ ordinary alef ا. */
    @Test
    fun normalizeArabicMapsAlefWasla() {
        val uthmani = "ٱلدِّينِ"
        val imlaei = "الدِّينِ"
        assertEquals("الدين", TajweedLexicalScoring.normalizeArabic(uthmani))
        assertEquals("الدين", TajweedLexicalScoring.normalizeArabic(imlaei))
        assertEquals(
            TajweedLexicalScoring.normalizeArabic(uthmani),
            TajweedLexicalScoring.normalizeArabic(imlaei),
        )
    }

    /** Quranic high sukun U+06E1 ↔ ordinary sukun U+0652. */
    @Test
    fun normalizeArabicMapsQuranicSukun() {
        val uthmani = "يَوۡمِ" // U+06E1
        val imlaei = "يَوْمِ" // U+0652
        assertEquals("يوم", TajweedLexicalScoring.normalizeArabic(uthmani))
        assertEquals("يوم", TajweedLexicalScoring.normalizeArabic(imlaei))
        assertEquals(
            TajweedLexicalScoring.normalizeArabic(uthmani),
            TajweedLexicalScoring.normalizeArabic(imlaei),
        )
    }

    /** Full Al-Fatiha 1:4 Uthmani (app expected) ↔ Imlaei ASR hyp — previously all SUB. */
    @Test
    fun normalizeArabicFatihah14UthmaniMatchesImlaeiAsr() {
        val uthmaniExpected = "مَٰلِكِ يَوۡمِ ٱلدِّينِ"
        val asrHypothesis = "مَالِكِ يَوْمِ الدِّينِ"
        val expWords = TajweedLexicalScoring.splitWords(uthmaniExpected)
        val hypWords = TajweedLexicalScoring.splitWords(asrHypothesis)
        assertEquals(3, expWords.size)
        assertEquals(3, hypWords.size)
        for (i in expWords.indices) {
            assertEquals(
                "word[$i] must match after normalize",
                TajweedLexicalScoring.normalizeArabic(expWords[i]),
                TajweedLexicalScoring.normalizeArabic(hypWords[i]),
            )
        }
        val ops = TajweedLexicalScoring.alignWords(expWords, hypWords)
        assertEquals(3, ops.size)
        assertTrue(ops.all { it.op == TajweedLexicalScoring.LexicalOp.MATCH })
        assertEquals(1.0, TajweedLexicalScoring.wordAccuracyScore(expWords, hypWords), 0.0001)
    }

    /** Ikhlas 112:1 Uthmani ↔ Imlaei — dagger/wasla/sukun cases together. */
    @Test
    fun normalizeArabicIkhlasUthmaniMatchesImlaei() {
        val uthmani = "قُلۡ هُوَ ٱللَّهُ أَحَدٌ"
        val imlaei = "قُلْ هُوَ اللَّهُ أَحَدٌ"
        val ops = TajweedLexicalScoring.alignWords(
            TajweedLexicalScoring.splitWords(uthmani),
            TajweedLexicalScoring.splitWords(imlaei),
        )
        assertTrue(ops.all { it.op == TajweedLexicalScoring.LexicalOp.MATCH })
    }

    @Test
    fun normalizeArabicKeepsGenuinelyDifferentWordsDistinct() {
        // Bare ملك (no alef) ≠ مالك (with alef) after canonical rules.
        assertNotEquals(
            TajweedLexicalScoring.normalizeArabic("ملك"),
            TajweedLexicalScoring.normalizeArabic("مالك"),
        )
        assertNotEquals(
            TajweedLexicalScoring.normalizeArabic("قُلْ"),
            TajweedLexicalScoring.normalizeArabic("قَالَ"),
        )
        assertNotEquals(
            TajweedLexicalScoring.normalizeArabic("رَبِّ"),
            TajweedLexicalScoring.normalizeArabic("رَبِّكَ"),
        )
    }

    @Test
    fun flutterErrorMappingPreservesNativeCode() {
        val native = TajweedNativeException(TajweedErrorCode.AUDIO_QUALITY_POOR, "too quiet")
        val code = TajweedChannelHandler.flutterCode(native)
        assertEquals(TajweedErrorCode.AUDIO_QUALITY_POOR, code)
        val fallback = TajweedChannelHandler.flutterCode(RuntimeException("boom"))
        assertEquals(TajweedErrorCode.INFERENCE_FAILED, fallback)
        assertFalse(fallback.isEmpty())
    }

    @Test
    fun sentencePieceTokenizerRoundTripsSimpleVocab() {
        val tmp = File.createTempFile("tokens_${UUID.randomUUID()}", ".txt")
        tmp.writeText("<unk> 0\n\u2581\u0628\u0633\u0645 1\n\u2581\u0627\u0644\u0644\u0647 2\n\u0645 3\n")
        try {
            val tokenizer = SentencePieceTokenizer(tmp)
            val ids = tokenizer.encode("\u0628\u0633\u0645 \u0627\u0644\u0644\u0647")
            assertTrue(ids.isNotEmpty())
            val decoded = tokenizer.decode(ids)
            assertTrue(decoded.contains("\u0628\u0633\u0645"))
        } finally {
            tmp.delete()
        }
    }

    /**
     * The forced-align -> word-grouping pipeline (TajweedEngine.buildWordLevelTokens) relies
     * on `startsNewWord` to know which pieces begin a new Quran word — this pins that raw
     * "▁" boundary detection independent of the head-model-dependent aggregation.
     */
    @Test
    fun startsNewWordDetectsSentencePieceWordBoundary() {
        val tmp = File.createTempFile("tokens_${UUID.randomUUID()}", ".txt")
        // ids: 0=<unk> 1=▁بسم(word start) 2=▁الله(word start) 3=م(continuation, no ▁)
        tmp.writeText("<unk> 0\n\u2581\u0628\u0633\u0645 1\n\u2581\u0627\u0644\u0644\u0647 2\n\u0645 3\n")
        try {
            val tokenizer = SentencePieceTokenizer(tmp)
            assertTrue(tokenizer.startsNewWord(1))
            assertTrue(tokenizer.startsNewWord(2))
            assertFalse(tokenizer.startsNewWord(3))
            assertFalse(tokenizer.startsNewWord(99)) // out-of-range id must not throw
        } finally {
            tmp.delete()
        }
    }
}
